version: "3.3"

services:
    rwkv:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: rwkv
      volumes:
        - ./app.py:/var/task/app.py
        - ./run.py:/var/task/models/run.py
      ports:
        - "9000:8080"
